"spindle_total_length"= 16cm
"spindle_center_radius" = 1.25cm
"bearing_spacing" = 5.5cm
"housing_inner_radius" = 3.cm
"housing_outer_radius"= 3.6cm
"bearing_width"= 1.66cm
"endcap_thickness"= 1cm
"bearing_outer_radius"= 2.25cm
"bearing_inner_radius"= 1cm
"endcap_insert_length"= 0.5cm
"D1@Sketch Spindle YZ Skeleton"="bearing_inner_radius"*2
"D2@Sketch Spindle YZ Skeleton"="spindle_total_length"
"D3@Sketch Spindle YZ Skeleton"="spindle_center_radius"*2
"D4@Sketch Spindle YZ Skeleton"="bearing_spacing"+"bearing_width"
"D6@Sketch Spindle YZ Skeleton"="bearing_width"
"D7@Sketch Spindle YZ Skeleton"="bearing_outer_radius"*2
"D8@Sketch Spindle YZ Skeleton"="housing_outer_radius"*2
"D9@Sketch Spindle YZ Skeleton"="bearing_outer_radius"*2
"D10@Sketch Spindle YZ Skeleton"="endcap_thickness"
"D11@Sketch Spindle YZ Skeleton"="endcap_insert_length"
"preload_washer_interface_width" = 0.5cm
"D12@Sketch Spindle YZ Skeleton"="preload_washer_interface_width"
